### ISSUE TITLE
Extension violates Chrome policies

### ISSUE THREAD

**Issue by Stackedstudio** [ivocass/instagram-redesigned#1]
I love it and want it back, is it possible to bring back on the webstore?
I know I can just download from here and run using developer mode but its ofcourse better if its back
<3

**Comment by ivocass** [comment]
Hello there! Thanks. The extension was taken down because of a trademark violation (the name and the logo). I had to submit it again under a new name ('Redesign for Instagram').
The Chrome team is currently reviewing the extension, so it should be live soon.
I've just pushed the latest updates, so in the meantime, feel free to pull the code and load it unpacked or package it.
I'll close this issue once the new extension goes live.

**Comment by ivocass** [comment]
The extension was approved and live at: https://chrome.google.com/webstore/detail/redesign-for-instagram/lhgbjhmblmfcgaklgpiebkeecgpkejhf
