### ISSUE TITLE
recent instagram update seems to have broken it again

### ISSUE THREAD

**Issue by JasonBall34** [ivocass/instagram-redesigned#6]
sorry

**Comment by ivocass** [comment]
@JasonBall34 thanks for reaching out.
Would you please describe the problem?

**Comment by ivocass** [comment]
@JasonBall34 thanks for letting me know.

I now see that Instagram reported the extension:
"The app infringes Instagram’s rights in the registered INSTAGRAM mark by using “for Instagram” in the app branding without any other branding that is distinctive to the app. Such use is likely to create confusion by implying an association or other relationship with, or authorization by, Instagram when no such relationship or authorization exists."

Regarding the story videos, that feature is not working right now because Instagram changed the code to make it harder to get the video's URL.
In the meantime, you can use [https://www.storysaver.net](https://www.storysaver.net)

I'll let you know here when I reupload the extension under a new name.

**Comment by ivocass** [comment]
Hey @JasonBall34, I've published the extension under a new name.
It's now called "Social redesign".

Here's the link https://chrome.google.com/webstore/detail/social-redesign/fogcfagnihhjclemiamiaofgcbjgleop
